# .github/workflows/heroku-deploy.yml
name: CI
on:
  push:
    branches: [main]
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: "17.1.0"
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: axex
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
