# .github/workflows/heroku-deploy.yml
name: Deploy To Heroku
on:
  push:
    branches: [main]

env:
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  MONGO_DEV_URL: ${{ secrets.MONGO_DEV_URL }}
  MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
  SUPER_USER_EMAIL: ${{ secrets.SUPER_USER_EMAIL }}
  SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
  API_URL: ${{ secrets.API_URL }}
  SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: "17.1.0"
      - name: Install dependencies
        run: yarn
      - name: Run Lint
        run: yarn lint
      - name: Run Tests
        run: yarn test
      - name: Run Build
        run: yarn build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: axex
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
