# This is a basic workflow to help you get started with Actions

name: Axex CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  MONGO_DEV_URL: ${{ secrets.MONGO_DEV_URL }}
  MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
  SUPER_USER_EMAIL: ${{ secrets.SUPER_USER_EMAIL }}
  SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
  API_URL: ${{ secrets.API_URL }}
  SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.1.0
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
